# Generated by Django 3.1.2 on 2020-11-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Тема')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_bool', models.BooleanField(verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.scale')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='top_scale',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Scale'),
        ),
    ]
