# Generated by Django 3.1.2 on 2020-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201106_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scale',
            new_name='Scope',
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='scale',
            new_name='scope',
        ),
        migrations.RemoveField(
            model_name='article',
            name='top_scale',
        ),
        migrations.AddField(
            model_name='article',
            name='top_scope',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Scope'),
        ),
    ]
