# Generated by Django 3.1.2 on 2020-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201106_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='main_bool',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
