# Generated by Django 3.1.2 on 2020-11-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201110_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='top_scope',
            new_name='scopes',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='main_bool',
            new_name='main',
        ),
    ]
